import {
  Activity,
  Anchor,
  Archive,
  Award,
  BarChart3,
  Beaker,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  Car,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Droplet,
  File,
  FileText,
  Filter,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  Image,
  Inbox,
  Key,
  Layers,
  Leaf,
  Lightbulb,
  LineChart,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Package,
  Phone,
  PieChart,
  Pin,
  Pizza,
  Plane,
  Receipt,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Tent,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Umbrella,
  Users,
  Video,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type IconEntry = {
  name: string;
  label: string;
  keywords: string;
  Icon: LucideIcon;
};

/** Curadoria de ~75 ícones úteis pra times de produto/marketing/ops/dev. */
export const ICONS: IconEntry[] = [
  { name: "briefcase", label: "Maleta", keywords: "trabalho negocio", Icon: Briefcase },
  { name: "building", label: "Prédio", keywords: "empresa escritorio", Icon: Building },
  { name: "building2", label: "Empresa", keywords: "corporativo", Icon: Building2 },
  { name: "users", label: "Equipe", keywords: "pessoas time", Icon: Users },
  { name: "heart", label: "Coração", keywords: "favorito amor", Icon: Heart },
  { name: "star", label: "Estrela", keywords: "destaque favorito", Icon: Star },
  { name: "award", label: "Prêmio", keywords: "conquista", Icon: Award },
  { name: "trophy", label: "Troféu", keywords: "vitoria", Icon: Trophy },
  { name: "target", label: "Alvo", keywords: "meta objetivo", Icon: Target },
  { name: "flag", label: "Bandeira", keywords: "marco milestone", Icon: Flag },
  { name: "bookmark", label: "Marcador", keywords: "salvar", Icon: Bookmark },
  { name: "pin", label: "Pin", keywords: "fixar", Icon: Pin },
  { name: "tag", label: "Tag", keywords: "etiqueta categoria", Icon: Tag },
  { name: "code", label: "Código", keywords: "dev engenharia", Icon: Code },
  { name: "terminal", label: "Terminal", keywords: "console cli", Icon: Terminal },
  { name: "database", label: "Banco", keywords: "dados database", Icon: Database },
  { name: "server", label: "Servidor", keywords: "backend infra", Icon: Server },
  { name: "cpu", label: "CPU", keywords: "processador chip", Icon: Cpu },
  { name: "cloud", label: "Nuvem", keywords: "cloud aws", Icon: Cloud },
  { name: "globe", label: "Globo", keywords: "web internet mundo", Icon: Globe },
  { name: "lock", label: "Cadeado", keywords: "seguranca privado", Icon: Lock },
  { name: "shield", label: "Escudo", keywords: "seguranca", Icon: Shield },
  { name: "key", label: "Chave", keywords: "acesso senha", Icon: Key },
  { name: "git-branch", label: "Branch", keywords: "git versao", Icon: GitBranch },
  { name: "shopping-bag", label: "Sacola", keywords: "compras ecommerce", Icon: ShoppingBag },
  { name: "shopping-cart", label: "Carrinho", keywords: "compras pedido", Icon: ShoppingCart },
  { name: "credit-card", label: "Cartão", keywords: "pagamento", Icon: CreditCard },
  { name: "dollar", label: "Dólar", keywords: "dinheiro receita", Icon: DollarSign },
  { name: "wallet", label: "Carteira", keywords: "dinheiro", Icon: Wallet },
  { name: "receipt", label: "Recibo", keywords: "nota fiscal", Icon: Receipt },
  { name: "trending-up", label: "Tendência", keywords: "crescimento growth", Icon: TrendingUp },
  { name: "bar-chart", label: "Gráfico barras", keywords: "metricas dados", Icon: BarChart3 },
  { name: "line-chart", label: "Gráfico linha", keywords: "metricas tendencia", Icon: LineChart },
  { name: "pie-chart", label: "Pizza", keywords: "metricas proporcao", Icon: PieChart },
  { name: "activity", label: "Atividade", keywords: "saude pulse", Icon: Activity },
  { name: "file-text", label: "Documento", keywords: "doc texto", Icon: FileText },
  { name: "file", label: "Arquivo", keywords: "documento", Icon: File },
  { name: "folder", label: "Pasta", keywords: "diretorio", Icon: Folder },
  { name: "archive", label: "Arquivo morto", keywords: "histórico", Icon: Archive },
  { name: "inbox", label: "Caixa", keywords: "entrada email", Icon: Inbox },
  { name: "mail", label: "Email", keywords: "correio mensagem", Icon: Mail },
  { name: "message-square", label: "Mensagem", keywords: "chat conversa", Icon: MessageSquare },
  { name: "phone", label: "Telefone", keywords: "ligacao contato", Icon: Phone },
  { name: "calendar", label: "Calendário", keywords: "agenda data", Icon: Calendar },
  { name: "clock", label: "Relógio", keywords: "tempo hora", Icon: Clock },
  { name: "book", label: "Livro", keywords: "leitura conhecimento", Icon: Book },
  { name: "book-open", label: "Livro aberto", keywords: "leitura aprender", Icon: BookOpen },
  { name: "settings", label: "Configurações", keywords: "engrenagem config", Icon: Settings },
  { name: "wrench", label: "Chave inglesa", keywords: "ferramenta", Icon: Wrench },
  { name: "hammer", label: "Martelo", keywords: "ferramenta construcao", Icon: Hammer },
  { name: "beaker", label: "Béquer", keywords: "experimento lab", Icon: Beaker },
  { name: "flask", label: "Frasco", keywords: "lab quimica experimento", Icon: FlaskConical },
  { name: "lightbulb", label: "Lâmpada", keywords: "ideia inovacao", Icon: Lightbulb },
  { name: "zap", label: "Raio", keywords: "energia rapido sprint", Icon: Zap },
  { name: "sparkles", label: "Brilho", keywords: "ai ia novo", Icon: Sparkles },
  { name: "search", label: "Lupa", keywords: "buscar pesquisa", Icon: Search },
  { name: "filter", label: "Filtro", keywords: "filtrar segmentar", Icon: Filter },
  { name: "layers", label: "Camadas", keywords: "stack agrupamento", Icon: Layers },
  { name: "box", label: "Caixa", keywords: "produto pacote", Icon: Box },
  { name: "package", label: "Pacote", keywords: "entrega produto", Icon: Package },
  { name: "rocket", label: "Foguete", keywords: "lancamento launch", Icon: Rocket },
  { name: "camera", label: "Câmera", keywords: "foto media", Icon: Camera },
  { name: "image", label: "Imagem", keywords: "foto arte", Icon: Image },
  { name: "video", label: "Vídeo", keywords: "filme media", Icon: Video },
  { name: "music", label: "Música", keywords: "audio som", Icon: Music },
  { name: "headphones", label: "Fones", keywords: "audio podcast", Icon: Headphones },
  { name: "mic", label: "Microfone", keywords: "audio podcast", Icon: Mic },
  { name: "megaphone", label: "Megafone", keywords: "marketing anuncio", Icon: Megaphone },
  { name: "bell", label: "Sino", keywords: "notificacao", Icon: Bell },
  { name: "monitor", label: "Monitor", keywords: "tela computador", Icon: Monitor },
  { name: "thumbs-up", label: "Curtir", keywords: "aprovacao", Icon: ThumbsUp },
  { name: "smile", label: "Sorriso", keywords: "feliz", Icon: Smile },
  { name: "coffee", label: "Café", keywords: "pausa break", Icon: Coffee },
  { name: "pizza", label: "Pizza", keywords: "comida", Icon: Pizza },
  { name: "gift", label: "Presente", keywords: "recompensa", Icon: Gift },
  { name: "plane", label: "Avião", keywords: "viagem travel", Icon: Plane },
  { name: "car", label: "Carro", keywords: "transporte", Icon: Car },
  { name: "truck", label: "Caminhão", keywords: "entrega logistica", Icon: Truck },
  { name: "map", label: "Mapa", keywords: "rota navegacao", Icon: MapIcon },
  { name: "map-pin", label: "Pino", keywords: "localizacao", Icon: MapPin },
  { name: "compass", label: "Bússola", keywords: "direcao", Icon: Compass },
  { name: "navigation", label: "Navegação", keywords: "direcao gps", Icon: Navigation },
  { name: "mountain", label: "Montanha", keywords: "desafio", Icon: Mountain },
  { name: "tent", label: "Tenda", keywords: "acampamento", Icon: Tent },
  { name: "graduation-cap", label: "Formatura", keywords: "educacao aprendizado", Icon: GraduationCap },
  { name: "anchor", label: "Âncora", keywords: "fixar estavel", Icon: Anchor },
  { name: "sun", label: "Sol", keywords: "dia claro", Icon: Sun },
  { name: "moon", label: "Lua", keywords: "noite escuro", Icon: Moon },
  { name: "droplet", label: "Gota", keywords: "agua liquido", Icon: Droplet },
  { name: "flame", label: "Chama", keywords: "fogo urgente", Icon: Flame },
  { name: "leaf", label: "Folha", keywords: "natureza sustentavel", Icon: Leaf },
  { name: "tree-pine", label: "Pinheiro", keywords: "natureza", Icon: TreePine },
  { name: "sprout", label: "Broto", keywords: "crescimento novo", Icon: Sprout },
  { name: "umbrella", label: "Guarda-chuva", keywords: "protecao chuva", Icon: Umbrella },
];

const ICON_MAP = new Map<string, LucideIcon>(
  ICONS.map((i) => [i.name, i.Icon]),
);

export function getIconByName(
  name: string | null | undefined,
): LucideIcon | null {
  if (!name) return null;
  return ICON_MAP.get(name) ?? null;
}

export type ColorEntry = {
  value: string;
  label: string;
};

/** Paleta de cores OKLCH curada — manter sincronizada com `--primary` e companhia. */
export const COLORS: ColorEntry[] = [
  { value: "oklch(0.66 0.19 264)", label: "Indigo" },
  { value: "oklch(0.65 0.18 145)", label: "Verde" },
  { value: "oklch(0.69 0.22 322)", label: "Magenta" },
  { value: "oklch(0.75 0.17 80)", label: "Âmbar" },
  { value: "oklch(0.66 0.16 230)", label: "Azul" },
  { value: "oklch(0.65 0.2 25)", label: "Vermelho" },
  { value: "oklch(0.68 0.13 200)", label: "Ciano" },
  { value: "oklch(0.55 0 0)", label: "Cinza" },
];
